# Generated by Django 3.1.3 on 2021-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('doro', models.CharField(max_length=100)),
                ('beonji', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
    ]
